# Generated by Django 5.1.7 on 2025-03-25 07:02

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WorkPattern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='更新日時')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='削除日時')),
                ('work_pattern_name', models.CharField(max_length=255, verbose_name='勤務形態名')),
                ('start_time', models.TimeField(verbose_name='勤務開始時間')),
                ('end_time', models.TimeField(verbose_name='勤務終了時間')),
                ('break_total_minute', models.IntegerField(default=0, verbose_name='1日の休憩時間')),
                ('note', models.CharField(blank=True, max_length=1000, null=True, verbose_name='備考')),
            ],
            options={
                'verbose_name': '勤務形態',
                'verbose_name_plural': '勤務形態',
                'db_table': 'work_patterns',
            },
        ),
    ]
