# Generated by Django 5.1.7 on 2025-03-25 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0004_attendancerecord"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="attendancerecord",
            options={"verbose_name": "勤怠", "verbose_name_plural": "勤怠"},
        ),
    ]
