# Generated by Django 5.1.7 on 2025-03-26 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0005_alter_attendancerecord_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='breaksetting',
            old_name='work_pattern_id',
            new_name='work_pattern',
        ),
    ]
