# Generated by Django 5.1.7 on 2025-04-02 06:02

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0006_rename_work_pattern_id_breaksetting_work_pattern'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AttendanceRecord',
            new_name='Record',
        ),
    ]
