# Generated by Django 5.1.7 on 2025-03-25 03:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("staff_hub", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="staff_hub.organization",
                verbose_name="組織",
            ),
        ),
    ]
