# Generated by Django 5.1.7 on 2025-03-25 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("staff_hub", "0002_alter_user_organization"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_staff",
            field=models.BooleanField(default=False),
        ),
    ]
