# Generated by Django 5.1.7 on 2025-03-25 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff_hub', '0003_user_is_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=255, verbose_name='ニックネーム'),
        ),
    ]
