# Generated by Django 5.1.7 on 2025-04-15 02:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff_hub', '0010_remove_permission_staff_hub_access'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='permission',
            name='master_data_access',
        ),
    ]
