# Generated by Django 5.1.7 on 2025-05-09 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("staff_hub", "0012_organizationmember"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="name",
            field=models.CharField(max_length=255, verbose_name="名前"),
        ),
    ]
