# Generated by Django 5.1.7 on 2025-05-09 05:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff_hub', '0013_alter_user_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrganizationMember',
        ),
    ]
