MESSAGES = {
    "RECEIVE_STOCK": "{added_qty} 個受け入れました。",
    "RECEIVE_STOCK_ERROR": "受け入れ数は 1 以上である必要があります。",
    "SEND_MAIL": "メールを送信しました。",
    "SEND_MAIL_EXECUTE_ERROR": "メール送信に失敗しました。時間をおいて再度実行してください。この状態が長く続くようでしたら、管理者にお問い合わせください。",
    "USE_STOCK": "{used_qty} 個使用しました。",
    "USE_STOCK_ERROR": "在庫が不足しています。",
    "MAIL_GROUP_DELETE_ERROR": "このグループを削除する権限がありません。",
    "MAIL_GROUP_DETAIL_BULK_CREATE": "宛先を一括登録しました。",
    "MAIL_GROUP_DETAIL_BULK_CREATE_ERROR": "宛先を1件以上指定してください。",
    "MAIL_GROUP_SEND_ERROR": "このグループへの送信権限がありません。",
    "SEND_MAIL_ERROR": "送信先ユーザーにメールアドレスが設定されていません。",
    "MONTH_PARAM_ERROR": "month パラメータは必須です。",
    "INVALID_MONTH_FORMAT": "無効な月の形式です。YYYY-MM の形式で指定してください。",
    "CLOCK_ORDER_ERROR": "退勤時間は出勤時間より後である必要があります。",
    "WORK_PATTERN_ERROR": "勤務時間が勤務形態の勤務時間外です。",
    "BREAK_TIME_ERROR": "休憩時間が勤務時間を超えています。",
    "DUPLICATE_RECORD_ERROR": "この勤務日はすでに記録されています。",
    "MONTH_PARAM_ERROR_RESPONSE": {"detail": "month パラメータは必須です。"},
    "INVALID_MONTH_FORMAT_RESPONSE": {"detail": "無効な月の形式です。YYYY-MM の形式で指定してください。"},
    "EMAIL_REQUIRED": "メールアドレスは必須です。",
}
