# Generated by Django 5.1.7 on 2025-03-28 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mail", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="mailgroupdetail",
            old_name="create_user",
            new_name="recipient_user",
        ),
    ]
