# Generated by Django 5.1.7 on 2025-04-04 05:28

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mail", "0003_rename_mailtemplate_mailhistory_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name="MailGroupDetail",
            new_name="MailGroupRecord",
        ),
        migrations.RenameField(
            model_name="mailgrouprecord",
            old_name="mail_group_detail",
            new_name="mail_group_record",
        ),
    ]
