from apps.attendance.views.attendance_record_view import AttendanceRecordView
from apps.attendance.views.attendance_record_my_list_view import AttendanceRecordMyListView
from apps.attendance.views.attendance_record_all_list_view import AttendanceRecordAllListView
from apps.attendance.views.attendance_record_detail_view import AttendanceRecordDetailView
