# Generated by Django 5.1.7 on 2025-03-25 13:44

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("trade_flow", "0002_order"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Defect",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="作成日時"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, null=True, verbose_name="更新日時"
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="削除日時"
                    ),
                ),
                ("occurred_at", models.DateTimeField(verbose_name="発生日時")),
                ("title", models.CharField(max_length=255, verbose_name="タイトル")),
                (
                    "defect_detail",
                    models.CharField(max_length=2000, verbose_name="不具合詳細"),
                ),
                ("submission", models.CharField(max_length=2000, verbose_name="対策")),
                ("submission_deadline", models.DateTimeField(verbose_name="対策期限")),
                (
                    "create_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="作成者",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="trade_flow.order",
                        verbose_name="注文",
                    ),
                ),
            ],
            options={
                "verbose_name": "不具合連絡",
                "verbose_name_plural": "不具合連絡",
                "db_table": "defects",
            },
        ),
    ]
