# Generated by Django 5.1.7 on 2025-03-25 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='material',
            options={'verbose_name': '資材', 'verbose_name_plural': '資材'},
        ),
        migrations.AlterField(
            model_name='material',
            name='material_name',
            field=models.CharField(max_length=255, verbose_name='資材名'),
        ),
        migrations.AlterField(
            model_name='material',
            name='material_price',
            field=models.FloatField(blank=True, null=True, verbose_name='資材価格'),
        ),
    ]
