# Generated by Django 5.1.7 on 2025-03-26 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "material",
            "0002_alter_material_options_alter_material_material_name_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="material",
            old_name="organizations_id",
            new_name="organization",
        ),
    ]
