# Generated by Django 5.1.7 on 2025-03-25 09:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='更新日時')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='削除日時')),
                ('customer_name', models.CharField(max_length=100, verbose_name='顧客名')),
                ('telephone', models.CharField(blank=True, max_length=100, null=True, verbose_name='電話番号')),
                ('fax', models.CharField(blank=True, max_length=100, null=True, verbose_name='FAX番号')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='メールアドレス')),
                ('postal_code', models.CharField(blank=True, max_length=100, null=True, verbose_name='郵便番号')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='住所')),
                ('client_contact', models.CharField(blank=True, max_length=100, null=True, verbose_name='客先担当者名')),
                ('internal_contact', models.CharField(blank=True, max_length=100, null=True, verbose_name='弊社担当者名')),
                ('note', models.TextField(blank=True, max_length=1000, null=True, verbose_name='備考')),
            ],
            options={
                'verbose_name': '顧客',
                'verbose_name_plural': '顧客',
                'db_table': 'customers',
            },
        ),
    ]
