# Generated by Django 5.1.7 on 2025-03-25 08:36

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('staff_hub', '0007_alter_permission_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='更新日時')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='削除日時')),
                ('plan_date', models.DateField(verbose_name='計画日')),
                ('note', models.CharField(blank=True, max_length=1000, null=True, verbose_name='備考')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff_hub.organization', verbose_name='組織')),
            ],
            options={
                'verbose_name': '生産計画',
                'verbose_name_plural': '生産計画',
                'db_table': 'production_plans',
            },
        ),
    ]
