from .mail_group_view import MailGroupView
from .mail_group_bulk_create_view import MailGroupBulkCreateView
from .mail_group_record_view import MailGroupRecordView
from .mail_send_view import MailSendView
