from .mail_group_view import MailGroupView
from .mail_group_bulk_create_view import MailGroupBulkCreateView
from .mail_group_detail_view import MailGroupDetailView
from .mail_send_view import MailSendView
